# Generated by Django 4.1 on 2022-08-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='holidayname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
