# Generated by Django 4.1 on 2022-08-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0003_employee_status_holiday_holidayname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
