# Generated by Django 4.1 on 2022-08-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='departmentname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
