# Generated by Django 4.1 on 2022-08-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('iconurl', models.CharField(max_length=126)),
            ],
            options={
                'db_table': 'propertytype',
            },
        ),
    ]
