# Generated by Django 4.1 on 2022-08-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0007_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='taskid',
            field=models.IntegerField(null=True),
        ),
    ]
