# Generated by Django 4.1 on 2022-11-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0008_taskactivity_taskid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dharani',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prelimtaskid', models.IntegerField()),
                ('requestid', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('district', models.CharField(max_length=100, null=True)),
                ('mandal', models.CharField(max_length=100, null=True)),
                ('village', models.CharField(max_length=100, null=True)),
                ('surveyno', models.CharField(max_length=100, null=True)),
                ('extent', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('pattadharname', models.CharField(max_length=100, null=True)),
                ('isdigitallysigned', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'dharani',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('task', models.CharField(max_length=1)),
                ('filename', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=1)),
                ('filecontent', models.BinaryField(null=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Preliminary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('startdate', models.DateTimeField(null=True)),
                ('donedate', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'preliminary',
            },
        ),
        migrations.CreateModel(
            name='PreliminaryTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tasktype', models.CharField(max_length=1, null=True)),
                ('prelimid', models.IntegerField(null=True)),
                ('requestid', models.IntegerField(null=True)),
                ('assignedto', models.IntegerField(null=True)),
                ('verifiedby', models.IntegerField(null=True)),
                ('assigneddate', models.DateTimeField(null=True)),
                ('completeddate', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=1, null=True)),
                ('notes', models.CharField(max_length=512, null=True)),
                ('remarks', models.CharField(max_length=512, null=True)),
                ('entryhours', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('verifyhours', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'preliminarytask',
            },
        ),
        migrations.CreateModel(
            name='RequestDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceid', models.IntegerField()),
                ('requestername', models.CharField(max_length=100)),
                ('requestermobilestatus', models.CharField(max_length=1, null=True)),
                ('requesteremail', models.CharField(max_length=100, null=True)),
                ('requestermobile', models.CharField(max_length=100, null=True)),
                ('requesteremailstatus', models.CharField(max_length=1, null=True)),
                ('requesteraddressline1', models.CharField(max_length=100, null=True)),
                ('requesteraddressline2', models.CharField(max_length=100, null=True)),
                ('requestercity', models.CharField(max_length=100, null=True)),
                ('requesterstate', models.CharField(max_length=100, null=True)),
                ('requestercountry', models.CharField(max_length=100, null=True)),
                ('requesterpin', models.CharField(max_length=10, null=True)),
                ('requesteridentitytype', models.CharField(max_length=1, null=True)),
                ('requesteridentitynumber', models.CharField(max_length=45, null=True)),
                ('agentcode', models.CharField(max_length=15, null=True)),
                ('requeststatus', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'requestdb',
            },
        ),
        migrations.CreateModel(
            name='RequestProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField(null=True)),
                ('ispropertylisted', models.CharField(max_length=1)),
                ('propertylocation', models.CharField(max_length=100, null=True)),
                ('propertyrevenuevillage', models.CharField(max_length=100, null=True)),
                ('propertymandal', models.CharField(max_length=100, null=True)),
                ('propertydistrict', models.CharField(max_length=100, null=True)),
                ('propertytype', models.CharField(max_length=1, null=True)),
                ('layoutapprovedby', models.CharField(max_length=20, null=True)),
                ('approvalnumber', models.CharField(max_length=50, null=True)),
                ('locationgeotag', models.CharField(max_length=100, null=True)),
                ('latestsaledeedno', models.CharField(max_length=100, null=True)),
                ('latestsaledeedyear', models.IntegerField(null=True)),
                ('latestsaledeedsro', models.CharField(max_length=100, null=True)),
                ('venturename', models.CharField(max_length=100, null=True)),
                ('houseno', models.CharField(max_length=100, null=True)),
                ('wardorblocknumber', models.CharField(max_length=40, null=True)),
                ('areaname', models.CharField(max_length=100, null=True)),
                ('phase', models.CharField(max_length=40, null=True)),
                ('plotarea', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('constructedarea', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('plintharea', models.DecimalField(decimal_places=2, max_digits=13, null=True)),
                ('ispattedharinposession', models.CharField(max_length=1, null=True)),
                ('reasonfornotinposession', models.CharField(max_length=200, null=True)),
                ('ptinnumber', models.CharField(max_length=40, null=True)),
                ('anypreexistinglitigations', models.CharField(max_length=1, null=True)),
                ('buildingpermissionnumber', models.CharField(max_length=40, null=True)),
                ('layoutpermissionnumber', models.CharField(max_length=40, null=True)),
                ('buildingapprovaldoc', models.BinaryField(null=True)),
                ('layoutapprovaldoc', models.BinaryField(null=True)),
                ('extentin', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'requestproperty',
            },
        ),
    ]
