# Generated by Django 4.1 on 2022-11-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0009_dharani_document_preliminary_preliminarytask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibitedLand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prelimtaskid', models.IntegerField()),
                ('requestid', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('village', models.CharField(max_length=100, null=True)),
                ('surveyno', models.CharField(max_length=100, null=True)),
                ('extent', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('pattadharname', models.CharField(max_length=100, null=True)),
                ('natureofland', models.CharField(max_length=100, null=True)),
                ('landclassification', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'prohibitedland',
            },
        ),
    ]
