# Generated by Django 4.1 on 2022-11-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0010_prohibitedland'),
    ]

    operations = [
        migrations.AddField(
            model_name='preliminarytask',
            name='verifystatus',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
