# Generated by Django 4.1 on 2022-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0011_preliminarytask_verifystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encumbrance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('reqdocno', models.CharField(max_length=50, null=True)),
                ('doctype', models.CharField(max_length=40, null=True)),
                ('claimantname', models.CharField(max_length=100, null=True)),
                ('executantname', models.CharField(max_length=100, null=True)),
                ('surveyno', models.CharField(max_length=40, null=True)),
                ('extent', models.DecimalField(decimal_places=3, max_digits=20, null=True)),
                ('village', models.CharField(max_length=50, null=True)),
                ('mandal', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'encumbrance',
            },
        ),
    ]
