# Generated by Django 4.1 on 2022-11-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0012_encumbrance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=1)),
                ('question', models.CharField(max_length=512, null=True)),
                ('choice', models.CharField(max_length=40, null=True)),
                ('yestask', models.CharField(max_length=1, null=True)),
                ('notask', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('sno', models.IntegerField()),
                ('casenumber', models.CharField(max_length=40, null=True)),
                ('courtname', models.CharField(max_length=100, null=True)),
                ('petitioners', models.CharField(max_length=256, null=True)),
                ('defendants', models.CharField(max_length=256, null=True)),
                ('casestatus', models.CharField(max_length=1, null=True)),
                ('ordernumber', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'legalcase',
            },
        ),
        migrations.CreateModel(
            name='Urbanland',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qid', models.IntegerField()),
                ('response', models.CharField(max_length=512, null=True)),
                ('prelimurbancol', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'urbanland',
            },
        ),
    ]
