# Generated by Django 4.1 on 2022-12-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflowapp', '0013_checklist_legalcase_urbanland'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklistanswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('requestid', models.IntegerField()),
                ('task', models.CharField(max_length=1)),
                ('question', models.CharField(max_length=512, null=True)),
                ('choice', models.CharField(max_length=40, null=True)),
                ('answer', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'checklistanswer',
            },
        ),
        migrations.AddField(
            model_name='urbanland',
            name='requestid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
